/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as MenRouteImport } from './routes/men'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShortlistRouteImport } from './routes/shortlist'
import { Route as WomenRouteImport } from './routes/women'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsCollectionRouteImport } from './routes/collections.$collection'
import { Route as GenderCategoryBraceletsRouteImport } from './routes/$gender.category.bracelets'
import { Route as GenderCollectionsCollectionIndexRouteImport } from './routes/$gender.collections.$collection.index'
import { Route as GenderCollectionsCollectionSubcollectionIndexRouteImport } from './routes/$gender.collections.$collection.$subcollection.index'
import { Route as GenderCollectionsCollectionSubcollectionModelRouteImport } from './routes/$gender.collections.$collection.$subcollection.$model'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistRoute = ShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionRoute = CollectionsCollectionRouteImport.update({
  id: '/collections/$collection',
  path: '/collections/$collection',
  getParentRoute: () => rootRouteImport,
} as any)
const GenderCategoryBraceletsRoute = GenderCategoryBraceletsRouteImport.update({
  id: '/$gender/category/bracelets',
  path: '/$gender/category/bracelets',
  getParentRoute: () => rootRouteImport,
} as any)
const GenderCollectionsCollectionIndexRoute =
  GenderCollectionsCollectionIndexRouteImport.update({
    id: '/$gender/collections/$collection/',
    path: '/$gender/collections/$collection/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GenderCollectionsCollectionSubcollectionIndexRoute =
  GenderCollectionsCollectionSubcollectionIndexRouteImport.update({
    id: '/$gender/collections/$collection/$subcollection/',
    path: '/$gender/collections/$collection/$subcollection/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GenderCollectionsCollectionSubcollectionModelRoute =
  GenderCollectionsCollectionSubcollectionModelRouteImport.update({
    id: '/$gender/collections/$collection/$subcollection/$model',
    path: '/$gender/collections/$collection/$subcollection/$model',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier': typeof AtelierRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/films': typeof FilmsRoute
  '/men': typeof MenRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/shortlist': typeof ShortlistRoute
  '/women': typeof WomenRoute
  '/collections/$collection': typeof CollectionsCollectionRoute
  '/collections/': typeof CollectionsIndexRoute
  '/$gender/category/bracelets': typeof GenderCategoryBraceletsRoute
  '/$gender/collections/$collection/': typeof GenderCollectionsCollectionIndexRoute
  '/$gender/collections/$collection/$subcollection/$model': typeof GenderCollectionsCollectionSubcollectionModelRoute
  '/$gender/collections/$collection/$subcollection/': typeof GenderCollectionsCollectionSubcollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier': typeof AtelierRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/films': typeof FilmsRoute
  '/men': typeof MenRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/shortlist': typeof ShortlistRoute
  '/women': typeof WomenRoute
  '/collections/$collection': typeof CollectionsCollectionRoute
  '/collections': typeof CollectionsIndexRoute
  '/$gender/category/bracelets': typeof GenderCategoryBraceletsRoute
  '/$gender/collections/$collection': typeof GenderCollectionsCollectionIndexRoute
  '/$gender/collections/$collection/$subcollection/$model': typeof GenderCollectionsCollectionSubcollectionModelRoute
  '/$gender/collections/$collection/$subcollection': typeof GenderCollectionsCollectionSubcollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier': typeof AtelierRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/films': typeof FilmsRoute
  '/men': typeof MenRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/shortlist': typeof ShortlistRoute
  '/women': typeof WomenRoute
  '/collections/$collection': typeof CollectionsCollectionRoute
  '/collections/': typeof CollectionsIndexRoute
  '/$gender/category/bracelets': typeof GenderCategoryBraceletsRoute
  '/$gender/collections/$collection/': typeof GenderCollectionsCollectionIndexRoute
  '/$gender/collections/$collection/$subcollection/$model': typeof GenderCollectionsCollectionSubcollectionModelRoute
  '/$gender/collections/$collection/$subcollection/': typeof GenderCollectionsCollectionSubcollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atelier'
    | '/contact'
    | '/faq'
    | '/films'
    | '/men'
    | '/rfq'
    | '/search'
    | '/shortlist'
    | '/women'
    | '/collections/$collection'
    | '/collections/'
    | '/$gender/category/bracelets'
    | '/$gender/collections/$collection/'
    | '/$gender/collections/$collection/$subcollection/$model'
    | '/$gender/collections/$collection/$subcollection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atelier'
    | '/contact'
    | '/faq'
    | '/films'
    | '/men'
    | '/rfq'
    | '/search'
    | '/shortlist'
    | '/women'
    | '/collections/$collection'
    | '/collections'
    | '/$gender/category/bracelets'
    | '/$gender/collections/$collection'
    | '/$gender/collections/$collection/$subcollection/$model'
    | '/$gender/collections/$collection/$subcollection'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atelier'
    | '/contact'
    | '/faq'
    | '/films'
    | '/men'
    | '/rfq'
    | '/search'
    | '/shortlist'
    | '/women'
    | '/collections/$collection'
    | '/collections/'
    | '/$gender/category/bracelets'
    | '/$gender/collections/$collection/'
    | '/$gender/collections/$collection/$subcollection/$model'
    | '/$gender/collections/$collection/$subcollection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtelierRoute: typeof AtelierRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FilmsRoute: typeof FilmsRoute
  MenRoute: typeof MenRoute
  RfqRoute: typeof RfqRoute
  SearchRoute: typeof SearchRoute
  ShortlistRoute: typeof ShortlistRoute
  WomenRoute: typeof WomenRoute
  CollectionsCollectionRoute: typeof CollectionsCollectionRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  GenderCategoryBraceletsRoute: typeof GenderCategoryBraceletsRoute
  GenderCollectionsCollectionIndexRoute: typeof GenderCollectionsCollectionIndexRoute
  GenderCollectionsCollectionSubcollectionModelRoute: typeof GenderCollectionsCollectionSubcollectionModelRoute
  GenderCollectionsCollectionSubcollectionIndexRoute: typeof GenderCollectionsCollectionSubcollectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlist': {
      id: '/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof ShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection': {
      id: '/collections/$collection'
      path: '/collections/$collection'
      fullPath: '/collections/$collection'
      preLoaderRoute: typeof CollectionsCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gender/category/bracelets': {
      id: '/$gender/category/bracelets'
      path: '/$gender/category/bracelets'
      fullPath: '/$gender/category/bracelets'
      preLoaderRoute: typeof GenderCategoryBraceletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gender/collections/$collection/': {
      id: '/$gender/collections/$collection/'
      path: '/$gender/collections/$collection'
      fullPath: '/$gender/collections/$collection/'
      preLoaderRoute: typeof GenderCollectionsCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gender/collections/$collection/$subcollection/': {
      id: '/$gender/collections/$collection/$subcollection/'
      path: '/$gender/collections/$collection/$subcollection'
      fullPath: '/$gender/collections/$collection/$subcollection/'
      preLoaderRoute: typeof GenderCollectionsCollectionSubcollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gender/collections/$collection/$subcollection/$model': {
      id: '/$gender/collections/$collection/$subcollection/$model'
      path: '/$gender/collections/$collection/$subcollection/$model'
      fullPath: '/$gender/collections/$collection/$subcollection/$model'
      preLoaderRoute: typeof GenderCollectionsCollectionSubcollectionModelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtelierRoute: AtelierRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FilmsRoute: FilmsRoute,
  MenRoute: MenRoute,
  RfqRoute: RfqRoute,
  SearchRoute: SearchRoute,
  ShortlistRoute: ShortlistRoute,
  WomenRoute: WomenRoute,
  CollectionsCollectionRoute: CollectionsCollectionRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  GenderCategoryBraceletsRoute: GenderCategoryBraceletsRoute,
  GenderCollectionsCollectionIndexRoute: GenderCollectionsCollectionIndexRoute,
  GenderCollectionsCollectionSubcollectionModelRoute:
    GenderCollectionsCollectionSubcollectionModelRoute,
  GenderCollectionsCollectionSubcollectionIndexRoute:
    GenderCollectionsCollectionSubcollectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
